# Generated by Django 4.0.6 on 2022-07-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('ref', models.CharField(max_length=200)),
                ('amount', models.PositiveBigIntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('currency_charged', models.CharField(max_length=3)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
